
//Login 登录
export const FETCH_USER_ERQ = 'FETCH_USER_ERQ'
export const FETCH_USER_SUC = 'FETCH_USER_SUC'
export const FETCH_USER_ERR = 'FETCH_USER_ERR'
export const FETCH_USER_USERINFO = 'FETCH_USER_USERINFO'
export const LOGOUT = 'LOGOUT'

//regist 注册
export const REGIST_SUC = 'REGIST_SUC'
export const REGIST_ERR = 'REGIST_ERR'

//toast 弹框
export const SHOW_TOAST = 'SHOW_TOAST'
export const HIDE_TOAST = 'HIDE_TOAST'
export const DEFINE_TOAST_MSG = 'DEFINE_TOAST_MSG'
export const DEFINE_TOAST_POSITION = 'DEFINE_TOAST_POSITION'

//index  首页

export const FETCH_INDEX_REQ = "FETCH_INDEX_REQ"
export const FETCH_INDEX_SUC = "FETCH_INDEX_SUC"
export const FETCH_INDEX_ERR = "FETCH_INDEX_ERR"
export const CLEAR_STATE_DATA = "CLEAR_STATE_DATA"
export const TOGGLE_NO_MORE_DATA_STATE = 'TOGGLE_NO_MORE_DATA_STATE'
export const TOGGLE_ERROR_DATA_STATE = 'TOGGLE_ERROR_DATA_STATE'
export const TOGGLE_ISFETCHING_STATE = 'TOGGLE_ISFETCHING_STATE'


//info  详情内容
export const FETCH_INFO_CON = 'FETCH_INFO_CON'
export const FETCH_INFO_COMMENT_DATA = 'FETCH_INFO_COMMENT_DATA'
export const NO_INFO_COMMENT_DATA = 'NO_INFO_COMMENT_DATA'
export const FETCH_INFO_FEEDBACKDATA = 'FETCH_INFO_FEEDBACKDATA'


//评论
export const SHOW_COMMENT_BAR = 'SHOW_COMMENT_BAR'
export const HIDE_COMMENT_BAR = 'HIDE_COMMENT_BAR'

export const IS_SEND_FEEDBACK = 'IS_SEND_FEEDBACK'
export const NO_SEND_FEEDBACK = 'NO_SEND_FEEDBACK'